<a href="https://colab.research.google.com/github/Krithika-Selvam/Machine-Learning/blob/main/full_data_process.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import pandas as pd
import numpy as np

In [59]:
df=pd.read_csv('testdata1.csv')
df.head()
df.isnull().any() 

cs41           False
cs42           False
cs43           False
alhpu          False
ashpu          False
10th           False
12th           False
att            False
fp/aarnps      False
travh          False
netcon         False
rev            False
semgpa         False
Unnamed: 13     True
Unnamed: 14     True
Unnamed: 15     True
Unnamed: 16     True
Unnamed: 17     True
Unnamed: 18     True
Unnamed: 19     True
Unnamed: 20     True
Unnamed: 21     True
dtype: bool

In [60]:
from sklearn.model_selection import train_test_split
x=df[['cs41','cs42','cs43','12th','att','fp/aarnps','travh','netcon','rev']].values
y=df['semgpa'].values
x

array([[82.17, 89.  , 85.59, ...,  0.  ,  1.  ,  1.  ],
       [35.5 , 40.33, 37.92, ...,  0.  ,  0.  ,  0.  ],
       [78.5 , 80.67, 79.59, ...,  0.  ,  1.  ,  0.  ],
       ...,
       [88.5 , 83.  , 85.75, ...,  0.  ,  0.  ,  1.  ],
       [72.83, 74.5 , 73.67, ...,  0.  ,  0.  ,  1.  ],
       [72.14,  0.  , 72.14, ...,  0.  ,  1.  ,  0.  ]])

In [172]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.009,random_state=42)
#normalize bteween 0 and 1
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)
x_train
x_test


array([[0.43942697, 0.32136683, 0.38015424, ..., 1.        , 1.        ,
        0.        ],
       [0.7664279 , 0.67965016, 0.72318766, ..., 0.        , 0.        ,
        1.        ],
       [0.87376726, 0.84745246, 0.86118252, ..., 0.        , 1.        ,
        1.        ],
       ...,
       [0.7664279 , 0.83728262, 0.80287918, ..., 1.        , 0.        ,
        1.        ],
       [0.8097166 , 0.75256788, 0.781491  , ..., 0.        , 0.        ,
        1.        ],
       [0.81490709, 0.9254551 , 0.8714653 , ..., 1.        , 1.        ,
        1.        ]])

In [173]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
model=Sequential()
model.add(Dense(10,activation='relu'))
model.add(Dense(10,activation='relu'))
model.add(Dense(10,activation='relu'))
model.add(Dense(10,activation='relu'))
model.add(Dense(10,activation='relu'))
model.add(Dense(10,activation='relu'))
model.add(Dense(10,activation='relu'))
model.add(Dense(10,activation='relu'))
model.add(Dense(10,activation='relu'))
model.add(Dense(10,activation='relu'))
model.add(Dense(10,activation='relu'))
#model.add(Dense(8,activation='relu'))
#model.add(Dense(8,activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam',loss='mse')


In [174]:
model.fit(x=x_train,y=y_train,epochs=250,validation_split=0.2)#one pass over the dataset

Epoch 1/250
633/633 [==============================] - 2s 2ms/step - loss: 2146.7126 - val_loss: 61.3180
Epoch 2/250
633/633 [==============================] - 1s 2ms/step - loss: 60.6944 - val_loss: 57.3407
Epoch 3/250
633/633 [==============================] - 1s 2ms/step - loss: 51.7526 - val_loss: 50.4626
Epoch 4/250
633/633 [==============================] - 1s 2ms/step - loss: 44.5169 - val_loss: 42.7559
Epoch 5/250
633/633 [==============================] - 1s 2ms/step - loss: 41.9767 - val_loss: 47.7914
Epoch 6/250
633/633 [==============================] - 1s 2ms/step - loss: 41.8745 - val_loss: 42.8759
Epoch 7/250
633/633 [==============================] - 1s 2ms/step - loss: 39.8288 - val_loss: 40.1359
Epoch 8/250
633/633 [==============================] - 1s 2ms/step - loss: 38.8595 - val_loss: 40.6054
Epoch 9/250
633/633 [==============================] - 1s 2ms/step - loss: 38.7551 - val_loss: 38.8160
Epoch 10/250
633/633 [==============================] - 1s 2ms/step - l

In [175]:
pd.DataFrame(model.history.history)

loss   val_loss
0    758.512939  61.318012
1     58.800995  57.340729
2     49.453209  50.462578
3     43.672321  42.755890
4     42.096333  47.791405
..          ...        ...
245   12.775047  13.157259
246   12.342156  13.169422
247   12.929530  11.658471
248   12.613048  11.428949
249   12.552985  11.532820

[250 rows x 2 columns]

In [176]:
model.evaluate(x_test,y_test,verbose=0)

13.632031440734863

In [177]:
model.evaluate(x_train,y_train,verbose=0)

11.57288932800293

In [178]:
test_predictions=model.predict(x_test)
test_predictions

array([[37.582012],
       [71.28223 ],
       [82.704735],
       [90.0647  ],
       [73.75593 ],
       [75.45652 ],
       [89.18362 ],
       [74.13223 ],
       [79.06832 ],
       [66.219406],
       [73.66265 ],
       [68.66762 ],
       [76.02906 ],
       [74.75957 ],
       [85.412796],
       [57.54115 ],
       [76.02801 ],
       [66.491585],
       [78.90931 ],
       [60.140987],
       [70.81266 ],
       [86.459435],
       [72.3541  ],
       [64.4137  ],
       [78.20411 ],
       [19.036116],
       [82.313385],
       [69.27754 ],
       [92.144135],
       [76.357506],
       [74.621475],
       [67.25148 ],
       [81.184395],
       [63.715748],
       [74.717766],
       [87.16746 ],
       [19.036116],
       [79.10786 ],
       [85.412796],
       [66.62005 ],
       [82.6208  ],
       [83.40343 ],
       [76.357506],
       [67.67273 ],
       [71.76032 ],
       [77.42922 ],
       [81.702576],
       [73.12334 ],
       [77.86296 ],
       [73.08141 ],


In [180]:
test_predictions=pd.Series(test_predictions.reshape(230,))
test_predictions

0      37.582012
1      71.282227
2      82.704735
3      90.064697
4      73.755928
         ...    
225    81.873390
226    67.688293
227    75.078163
228    73.157646
229    81.863609
Length: 230, dtype: float32

In [181]:
pred_df=pd.DataFrame(y_test,columns=['Prediction Values'])
pred_df=pd.concat([pred_df,test_predictions],axis=1)
pred_df.columns=['test true Y','model predictions']
pred_df

test true Y  model predictions
0          36.97          37.582012
1          66.20          71.282227
2          83.75          82.704735
3          89.25          90.064697
4          71.32          73.755928
..           ...                ...
225        77.00          81.873390
226        67.34          67.688293
227        71.25          75.078163
228        67.50          73.157646
229        84.75          81.863609

[230 rows x 2 columns]

In [182]:
from sklearn.metrics import mean_absolute_error,mean_squared_error
mean_absolute_error(pred_df['test true Y'],pred_df['model predictions'])

2.5745121478205144

In [183]:
import sklearn.metrics as sm
print("Mean absolute error =", round(sm.mean_absolute_error(pred_df['test true Y'],pred_df['model predictions']), 2)) 
print("Mean squared error =", round(sm.mean_squared_error(pred_df['test true Y'],pred_df['model predictions']), 2)) 
print("Median absolute error =", round(sm.median_absolute_error(pred_df['test true Y'],pred_df['model predictions']), 2)) 
print("Explain variance score =", round(sm.explained_variance_score(pred_df['test true Y'],pred_df['model predictions']), 2)) 
print("R2 score =", round(sm.r2_score(pred_df['test true Y'],pred_df['model predictions']), 2))

Mean absolute error = 2.57
Mean squared error = 13.63
Median absolute error = 1.85
Explain variance score = 0.92
R2 score = 0.92
