<a href="https://colab.research.google.com/github/Krithika-Selvam/Machine-Learning/blob/main/full_data_process.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import pandas as pd
import numpy as np

In [21]:
df=pd.read_csv('project.csv')
df.head()

cs41   cs42   cs43  alhpu  ashpu  ...  fp/aarnps  travh  netcon  rev  semgpa
0  82.17  89.00  85.59     12   15.6  ...          2      0       1    1   80.00
1  35.50  40.33  37.92     12   14.4  ...         14      0       0    0   68.60
2  78.50  80.67  79.59     12   14.4  ...          0      1       1    0   70.83
3  78.00  82.00  80.00     12   13.0  ...          0      0       1    0   74.60
4  67.17  70.17  68.67     12   11.0  ...          3      0       1    0   64.20

[5 rows x 13 columns]

In [48]:
from sklearn.model_selection import train_test_split
x=df[['cs41','cs42','cs43','10th','12th','att','fp/aarnps','travh','netcon','rev']].values
y=df['semgpa'].values
x

array([[82.17, 89.  , 85.59, ...,  0.  ,  1.  ,  1.  ],
       [35.5 , 40.33, 37.92, ...,  0.  ,  0.  ,  0.  ],
       [78.5 , 80.67, 79.59, ...,  1.  ,  1.  ,  0.  ],
       ...,
       [88.5 , 83.  , 85.75, ...,  1.  ,  0.  ,  1.  ],
       [72.83, 74.5 , 73.67, ...,  0.  ,  0.  ,  1.  ],
       [72.14,  0.  , 72.14, ...,  1.  ,  1.  ,  0.  ]])

In [82]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=42)
#normalize bteween 0 and 1
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)
x_train
x_test


array([[0.8003125 , 0.82202787, 0.81969429, 0.83836944, 0.76204101,
        0.57142857, 0.        , 0.1       , 1.        , 1.        ],
       [0.76041667, 0.74575409, 0.76084018, 0.80615735, 0.78159275,
        0.17857143, 0.16666667, 0.1       , 1.        , 1.        ],
       [0.88541667, 0.92209905, 0.91338255, 0.83751425, 0.77682403,
        0.57142857, 0.        , 0.        , 1.        , 1.        ],
       [0.85239583, 0.85599512, 0.86305501, 0.77194983, 0.91273247,
        0.39285714, 0.        , 0.        , 1.        , 1.        ],
       [0.76041667, 0.85599512, 0.81719871, 0.42987457, 0.56223176,
        0.60714286, 0.        , 0.        , 1.        , 0.        ],
       [0.55208333, 0.57632462, 0.5702402 , 0.75826682, 0.63423939,
        0.82142857, 0.5       , 0.        , 0.        , 0.        ],
       [0.859375  , 0.87287705, 0.87522096, 1.        , 0.90081068,
        0.25464286, 0.        , 0.1       , 1.        , 0.        ],
       [0.90447917, 0.89667446, 0.9098471

In [83]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
model=Sequential()
model.add(Dense(4,activation='relu'))
model.add(Dense(4,activation='relu'))
model.add(Dense(4,activation='relu'))
model.add(Dense(4,activation='relu'))
#model.add(Dense(4,activation='relu'))
#model.add(Dense(4,activation='relu'))
#model.add(Dense(4,activation='relu'))
model.add(Dense(1))
model.compile(optimizer='rmsprop',loss='mse')


In [84]:
model.fit(x=x_train,y=y_train,epochs=700)#one pass over the dataset

Epoch 1/700
9/9 [==============================] - 1s 2ms/step - loss: 5405.9439
Epoch 2/700
9/9 [==============================] - 0s 2ms/step - loss: 5306.9605
Epoch 3/700
9/9 [==============================] - 0s 1ms/step - loss: 5304.7900
Epoch 4/700
9/9 [==============================] - 0s 2ms/step - loss: 5405.7779
Epoch 5/700
9/9 [==============================] - 0s 2ms/step - loss: 5398.1443
Epoch 6/700
9/9 [==============================] - 0s 2ms/step - loss: 5181.3232
Epoch 7/700
9/9 [==============================] - 0s 2ms/step - loss: 5417.7025
Epoch 8/700
9/9 [==============================] - 0s 2ms/step - loss: 5410.2259
Epoch 9/700
9/9 [==============================] - 0s 2ms/step - loss: 5241.8274
Epoch 10/700
9/9 [==============================] - 0s 2ms/step - loss: 5259.8589
Epoch 11/700
9/9 [==============================] - 0s 2ms/step - loss: 5206.2286
Epoch 12/700
9/9 [==============================] - 0s 2ms/step - loss: 5126.2214
Epoch 13/700
9/9 [=======

In [74]:
pd.DataFrame(model.history.history)

loss
0    5368.412598
1    5363.380859
2    5360.889648
3    5358.311523
4    5355.410156
..           ...
695    69.580177
696    69.191513
697    69.753998
698    69.179138
699    69.178619

[700 rows x 1 columns]

In [85]:
model.evaluate(x_test,y_test,verbose=0)

72.1780776977539

In [86]:
model.evaluate(x_train,y_train,verbose=0)

67.47478485107422

In [87]:
test_predictions=model.predict(x_test)
test_predictions

array([[77.11554 ],
       [75.64612 ],
       [80.851006],
       [79.76748 ],
       [63.836647],
       [56.982723],
       [70.29955 ],
       [82.10767 ],
       [68.567535],
       [77.52082 ],
       [76.974945],
       [74.82065 ],
       [46.94175 ],
       [66.996376],
       [83.08142 ],
       [55.326885],
       [42.221935],
       [70.00005 ],
       [77.88083 ],
       [84.63338 ],
       [79.20201 ],
       [64.75747 ],
       [78.67705 ],
       [72.763245],
       [78.74853 ],
       [58.339092],
       [82.762955],
       [76.79492 ],
       [68.39766 ],
       [61.805813],
       [65.48371 ],
       [67.11298 ]], dtype=float32)

In [89]:
test_predictions=pd.Series(test_predictions.reshape(32,))
test_predictions


0     77.115540
1     75.646118
2     80.851006
3     79.767479
4     63.836647
5     56.982723
6     70.299553
7     82.107674
8     68.567535
9     77.520821
10    76.974945
11    74.820648
12    46.941750
13    66.996376
14    83.081421
15    55.326885
16    42.221935
17    70.000053
18    77.880829
19    84.633377
20    79.202011
21    64.757469
22    78.677048
23    72.763245
24    78.748528
25    58.339092
26    82.762955
27    76.794922
28    68.397659
29    61.805813
30    65.483711
31    67.112984
dtype: float32

In [90]:
pred_df=pd.DataFrame(y_test,columns=['Prediction Values'])
pred_df=pd.concat([pred_df,test_predictions],axis=1)
pred_df.columns=['test true Y','model predictions']
pred_df

test true Y  model predictions
0         78.83          77.115540
1         75.00          75.646118
2         87.84          80.851006
3         76.25          79.767479
4         66.50          63.836647
5         54.84          56.982723
6         70.40          70.299553
7         83.75          82.107674
8         65.00          68.567535
9         76.00          77.520821
10        78.92          76.974945
11        75.59          74.820648
12        34.00          46.941750
13        70.00          66.996376
14        97.25          83.081421
15        63.07          55.326885
16        14.67          42.221935
17        61.67          70.000053
18        82.50          77.880829
19        80.80          84.633377
20        75.40          79.202011
21        52.17          64.757469
22        85.42          78.677048
23        62.75          72.763245
24        81.25          78.748528
25        66.00          58.339092
26        70.00          82.762955
27        76.09          76.794922
28        75.60          68.397659
29        67.08          61.805813
30        50.42          65.483711
31        59.63          67.112984

In [91]:
from sklearn.metrics import mean_absolute_error,mean_squared_error
mean_absolute_error(pred_df['test true Y'],pred_df['model predictions'])

6.287794547080994